apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: eshop-productservice
      context: eshop-productservice
      docker:
        buildArgs:
          HTTP_PROXY: http://70.10.15.10:8080
          HTTPS_PROXY: http://70.10.15.10:8080
    - image: eshop-cartservice
      context: eshop-cartservice
      jib:
        type: gradle
    - image: eshop-backend
      context: eshop-backend
      jib:
        type: gradle
    - image: eshop-frontend
      context: eshop-frontend
deploy:
  kubectl:
    manifests:
      - k8s/**.yaml