apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: eshop-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: eshop-frontend
          servicePort: 80
      - path: /api
        backend:
          serviceName: eshop-backend
          servicePort: 8090
      - path: /api/carts
        backend:
          serviceName: eshop-cartservice
          servicePort: 8091